### ISSUE TITLE
Remove unused css

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#264]
```css
div.routine-heading div.row button.focus-investigation.btn.btn-primary {
    margin-top: 3rem !important;
    float: right;
}
```
